# mongo-express.yml

services:
  mongodb:
    image: mongo
    container_name: mongodb
    env_file: .env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
